/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoClerkRouteImport } from './routes/demo/clerk'
import { Route as ServerServerIdVoiceChannelIdRouteImport } from './routes/server/$serverId/voice/$channelId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoClerkRoute = DemoClerkRouteImport.update({
  id: '/demo/clerk',
  path: '/demo/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerServerIdVoiceChannelIdRoute =
  ServerServerIdVoiceChannelIdRouteImport.update({
    id: '/server/$serverId/voice/$channelId',
    path: '/server/$serverId/voice/$channelId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/server/$serverId/voice/$channelId': typeof ServerServerIdVoiceChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/server/$serverId/voice/$channelId': typeof ServerServerIdVoiceChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/server/$serverId/voice/$channelId': typeof ServerServerIdVoiceChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/demo/clerk'
    | '/server/$serverId/voice/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/demo/clerk' | '/server/$serverId/voice/$channelId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/demo/clerk'
    | '/server/$serverId/voice/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DemoClerkRoute: typeof DemoClerkRoute
  ServerServerIdVoiceChannelIdRoute: typeof ServerServerIdVoiceChannelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/clerk': {
      id: '/demo/clerk'
      path: '/demo/clerk'
      fullPath: '/demo/clerk'
      preLoaderRoute: typeof DemoClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server/$serverId/voice/$channelId': {
      id: '/server/$serverId/voice/$channelId'
      path: '/server/$serverId/voice/$channelId'
      fullPath: '/server/$serverId/voice/$channelId'
      preLoaderRoute: typeof ServerServerIdVoiceChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DemoClerkRoute: DemoClerkRoute,
  ServerServerIdVoiceChannelIdRoute: ServerServerIdVoiceChannelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
